- name: Main NGINX config file
  copy:
    src: nginx.conf # pas besoin de pr√©ciser de path, il sait qu'il doit chercher dans le dossier files/
    dest: /etc/nginx/nginx.conf
    mode: "0644"
    notify: restart nginx
